title: Christian Victor Tineo Quispe

logo: picture.png

description: Cloud Solutions Architect/SRE/DevOps

show_downloads: false

theme: jekyll-theme-hacker

plugins:
  - jekyll-seo-tag

email: christian.tineo.528@gmail.com
